PUT localhost:3000/60c5180221b2e34f580d1314
Authorization: psalvatore@blueedtech.com.br
Content-Type: application/json

{
  "nome": "Paulo Salvatore",
  "key": "value",
  "number": 1,
  "boolean": true,
  "object": {
    "key": "value"
  }
}
